FROM node:latest as builder

WORKDIR /app

COPY ./web/package*.json ./

RUN npm install

COPY ./web .

ENV VITE_SUGARPY_BASE_URL=https://sugarpy-976929012397.us-central1.run.app

RUN npm run build

FROM nginx:alpine

COPY ./nginx-default.conf.template /etc/nginx/conf.d/

COPY --from=builder /app/dist /usr/share/nginx/html

ENV PORT=8080

RUN envsubst '$PORT' < /etc/nginx/conf.d/nginx-default.conf.template > /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
