FROM node:latest as builder

WORKDIR /app

COPY ./web/package*.json ./

RUN npm install

RUN npm install toml

COPY ./web .

COPY get_version.cjs .

COPY pyproject.toml .

ENV VITE_SUGARPY_BASE_URL=https://sugarpy-976929012397.us-central1.run.app

RUN export VITE_SUGARPY_VERSION=$(node get_version.cjs) && \
    echo "VITE_SUGARPY_VERSION=$VITE_SUGARPY_VERSION" >> .env && \
    npm run build

FROM nginx:alpine

COPY ./nginx-default.conf.template /etc/nginx/conf.d/

COPY --from=builder /app/dist /usr/share/nginx/html

ENV PORT=8080

RUN envsubst '$PORT' < /etc/nginx/conf.d/nginx-default.conf.template > /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
